# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63cc9b33fb292379bec87a27c5b5b2a09752b79f8ea067a1182b2ad6f60c348c6906978721722ba662d16f2d997d8d35952fe558e77675e2b14483713a8e8bf5

test:
  secret_key_base: 96ba2d87a77ad64357b60368f1ae098e2330f64cbce9cbc10e673fc648ba75f6fa19fbdda5d9640712382b24691eccea8e1d55ca8354631319bb28e47f013b41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
